#version 450
layout(local_size_x = 4, local_size_y = 4) in;
layout (binding = 0, rgba8) uniform writeonly image2D writable_image;
layout (binding = 1, r32f) uniform readonly image3D readable_image;
layout (push_constant) uniform BockName {
  float var_float;
  int var_int;
} consts;
layout (binding = 2) uniform sampler2D texture_no_layout;
layout (location = 3, binding = 2, set = 1) uniform sampler2D texture_with_layout;
layout (binding = 3, std430) buffer ssbo_buffer {  float ssbo_buffer_floats[]; };
layout (binding = 4, std430) readonly buffer ssbo_buffer_ro {  float ssbo_buffer_floats_ro[]; };
layout (binding = 5,std430) writeonly buffer ssbo_buffer_wo {  float ssbo_buffer_floats_wo[]; };
struct ssbo_struct { float a; int b; };
layout (binding = 6, std430) buffer ssbo_buffer_sized {  ssbo_struct block_sized_struct;  };
layout (binding = 7) uniform sampler separate_sampler;
layout (binding = 8) uniform texture2D separate_image;
layout (binding = 9, std430) uniform ubo { float ubo_float; };
void main() {
  imageStore(writable_image, ivec2(0, 0), vec4(ssbo_buffer_floats[0]));
  ssbo_buffer_floats_wo[0] = ssbo_buffer_floats[0] + ssbo_buffer_floats_ro[0];
  block_sized_struct.a = ssbo_buffer_floats[0] + ssbo_buffer_floats_ro[0];
}
